Refactoring
HT808s/gofinance pull request #2
Opened 2016-12-26 16:48 UTC by HT808s

Hi tried to do a refactoring of the project in order to lay better foundation for the future work

2016-12-26 16:51 UTC, HT808s commented
@sklarsa Let me know what do you think of that change and don't hesitate to make suggestions !

2016-12-27 18:08 UTC, sklarsa requested changes
Just a few small changes to get everything to build... Aside from that, nice work!  I really like the refactor and the cli seems much cleaner than it was before.

2016-12-27 18:08 UTC, sklarsa commented on bloomberg/quote.go
> +	"github.com/aktau/gofinance/util"
Should be `github.com/HT808s/gofinance/util`

2016-12-27 18:08 UTC, sklarsa commented on glide.yaml
> +  - html
Missing `gopkg.in/alecthomas/kingpin.v2`

2016-12-27 18:08 UTC, sklarsa commented on glide.lock
> +  - unix
Missing `gopkg.in/alecthomas/kingpin.v2`

2016-12-27 19:16 UTC, HT808s commented
@sklarsa Thanks for your valuable review and pointing at me what I missed
Along with the fix I did some minor changes in the workflow 
* Add a `sources`directory on top of yahoofinance and bloomberg packages
* Removed the too "specialized" method `PrettyDisplay` in models/quote.qo to cmd/cli since it contains code which only concerns the terminal app

The code in models should be, if possible, agnostic

2016-12-27 19:41 UTC, sklarsa commented
Ya that makes sense to me.  I can make a PR for basic unit tests on the yahoo and bloomberg source APIs (since that's my primary use case at the moment) once this is merged.

2016-12-27 19:58 UTC, HT808s commented
I think it's good to merge
Unit tests will be nice !
Actually that's the next topic to take into consideration
I will think at how to improve the overall testability of the project along with it's integration to a CI

2016-12-27 21:08 UTC, sklarsa commented
I think we can probably use TravisCI since it's free for open source projects and has solid github integration... unless you have any other inclinations towards something else

2016-12-27 21:33 UTC, HT808s commented
TravisCi is ok with me
I'll check on that later

2016-12-27 22:04 UTC, merged